
name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]


jobs:
  package_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install package-lock
      run: npm ci
    - name: Install dependencies
      run: lerna bootstrap
    - name: Run lint tests
      run: lerna run lint
    - name: Attempt build
      run: lerna run build
    - name: Run typescript check
      run: lerna run test:ts